---
title: "Getting and Cleaning Data Course Project Codebook"
author: "Sonali Nimkar"
date: "April 11, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Approach

The script ``run_analysis.R`` performs the 5 steps described in the course project's definition.

First, all data are read from their respective files (train, test, features and activity labels). The column names for the data are set appropriately; after which, the data are combined using the ``cbind`` and ``rbind`` methods.

Then, as activity data are addressed with values 1:6, the activity names and Ids are taken from the file ``activity_labels.txt`` and they are substituted in the dataset.

Next, only those columns with the mean and standard deviation measures are extracted from the dataset; these columns are then given correct names, obtained from ``features.txt``.

Finally, a new dataset is generated - this contains the average measures for each subject and activity type (30 subjects * 6 activities = 180 rows). The output file is called ``tidydata.txt``.

