---
title: "Getting and Cleaning Data Course Project - Readme"
author: "Sonali Nimkar"
date: "April 11, 2016"
output: html_document
---

## Getting and Cleaning Data - Course Project

This is the course project for the Getting and Cleaning Data Coursera course. 
This project essentially assesses the ability of the student to load and clean a dataset in preparation for further analysis. 

"One of the most exciting areas in all of data science right now is wearable computing - see for example this article . Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone."
        ~ courtesy: Coursera team

The afore-mentioned dataset is used to glean only data of interest to further analysis. The process for doing so is explained below.

The R script, ``run_analysis.R``, does the following:

- Loads the datasets for training, testing, activity and feature info
- Loads the activity and subject data for each dataset, and merges those columns with the dataset
- In the train and test datasets, keeps only those columns which reflect a mean or standard deviation
- Merges the two datasets to make a single large dataset
- Creates a tidy dataset that consists of the average (mean) value of each variable for each subject and activity pair.
- The end result is shown in the file tidydata.txt.

